language: ruby
services:
- postgresql
env:
- "RAILS_ENV=test"
before_install:
- gem update --system --no-document
- gem install bundler -v 1.16.2 --no-document
before_script:
- RAILS_ENV=test bin/rake db:create db:migrate
addons:
  postgresql: "9.6"
  code_climate:
    repo_token: 1a61897ad8498cf2a3cd582b162903dd5e306ba7d4403e889dd0dc949d761460
after_success:
- bundle exec codeclimate-test-reporter